CREATE TABLE admins (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255),
  phone VARCHAR(255),
  password VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE drivers (
  licence VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255),
  phone VARCHAR(255),
  password VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE parents (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255),
  phone VARCHAR(255),
  password VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE routes (
  id INT PRIMARY KEY,
  name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE stops (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255),
  latitude DECIMAL(10, 8),
  longitude DECIMAL(11, 8),
  route_id INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (route_id) REFERENCES routes(id)
);


CREATE TABLE buses (
  plate_number VARCHAR(255) PRIMARY KEY,
  driver_id VARCHAR(255),
  route_id INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (driver_id) REFERENCES drivers(licence),
  FOREIGN KEY (route_id) REFERENCES routes(id)
);

CREATE TABLE students (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255),
  grade_level VARCHAR(255),
  parent_id VARCHAR(255),
  bus_assigned VARCHAR(255),
  stop_id INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (parent_id) REFERENCES parents(id),
  FOREIGN KEY (bus_assigned) REFERENCES buses(plate_number),
  FOREIGN KEY (stop_id) REFERENCES stops(id)
);

CREATE TABLE locations (
  id INT PRIMARY KEY,
  bus_plate_number VARCHAR(255),
  latitude DECIMAL(10,8),
  longitude DECIMAL(11,8),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (bus_plate_number) REFERENCES buses(plate_number)
);

CREATE TABLE messages (
  id INT PRIMARY KEY,
  sender_id VARCHAR(255),
  recipient_id VARCHAR(255),
  content TEXT,
  sent_at DATETIME,
  received_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (sender_id) REFERENCES admins(id) ON DELETE CASCADE,
  FOREIGN KEY (sender_id) REFERENCES drivers(licence) ON DELETE CASCADE,
  FOREIGN KEY (sender_id) REFERENCES parents(id) ON DELETE CASCADE,
  FOREIGN KEY (recipient_id) REFERENCES admins(id) ON DELETE CASCADE,
  FOREIGN KEY (recipient_id) REFERENCES drivers(licence) ON DELETE CASCADE,
  FOREIGN KEY (recipient_id) REFERENCES parents(id) ON DELETE CASCADE
);

